
* Texte d'accompagnement Traces 01

### Jeux de données pour publication (Traces 01)

Les jeux de données sont dans le dossier partagé // Traces 01 // Données.
https://mindsized.org/owncloud/public.php?service=files&t=b9b1e9aba8629c76218cff2b0c73c04a

#### Description du jeu avant anonymisation

Dans son système d'information (dans Apogée), l'Université Paris 13 a relevé, pour chaque année universitaire entre 2006(-2007) et 2015(-2016), les données sur l'inscription des étudiant·e·s dans des étapes d'une année en vue de préparer un diplôme. Les données relevées sont les suivantes.

| Colonne                  | Explication                                                      |
|:--------------------------|:------------------------------------------------------------------|
| CODE_INDIVIDU             | Donnée masquée                                                   |
| ANNEE_INSCRIPTION         | Année d'inscription : 2006 pour 2006-2007, etc.                  |
| LIB_DIPLOME               | Nom du diplôme                                                   |
| NIVEAU_DANS_LE_DIPLOME      | 1, 2,… pour master 1 ou licence 1, master 2 etc.                 |
| NIVEAU_APRES_BAC           | 1, 2,… pour Bac+1, Bac+2,…                                       |
| LIBELLE_DISCIPLINE_DIPLOME | Rattachement du diplôme à une discipline                         |
| CODE_SISE_DIPLOME          | Code diplôme du système d’information sur le suivi de l’étudiant |
| CODE_ETAPE                | Code interne d'une étape (année, parcours) de diplôme            |
| LIBELLE_COURT_ETAPE        | Nom court de l'étape                                             |
| LIBELLE_LONG_ETAPE         | Nom plus intelligible de l'étape                                 |
| LIBELLE_COURT_COMPOSANTE   | Nom de la composante (UFR, IUT etc.)                             |
| CODE_COMPOSANTE           | Code numérique de la composante (inutilisé)                      |
| REGROUPEMENT_BAC          | Type de Bac (L, ES, S, techno STMG, techno ST2S,…)               |
| LIBELLE_ACADEMIE_BAC       | Académie du Bac (Créteil, Versailles, étranger,…)                |
| CONTINENT                | Déduit de la nationalité (donnée masquée)                        |
| LIBELLE_REGIME            | Formation initiale, continue, pro, apprentissage                 |
| NIEME_INSCRIPTION         | Nombre d'inscriptions à Paris 13                                 |

D'autres données telle que l'adresse des étudiant·e·s sont en cours d'anonymisation pour une prochaine ouverture.

#### Toilettage du jeu de donné initial
Le jeu de données initial contient des données "singulières" au sens ou des valeurs apparaissent moins de 5 fois en tout et pour tout. Pour le dire autrement il y a des colonnes pour lesquelles des lignes prennent des valeurs rares. On commence par supprimer ces lignes, pour chaque colonne et en travaillant récursivement.

Le nombre initial de lignes, dans la donnée brute était de 213 289. En une première passe d'anonymisation voici le nom des colonnes et le nombre de valeurs rares (moins de 5 occurences) par colonne :

| Colonne | nombre de valeurs rares |
|-----:|:---|
|LIB_DIPLOME | 1|
|LIBELLE_DISCIPLINE_DIPLOME| 27|
|CODE_SISE_DIPLOME| 41|
|CODE_ETAPE| 319|
|LIBELLE_COURT_ETAPE| 299|
|LIBELLE_LONG_ETAPE|362|
|NIEME_INSCRIPTION|3|

Après suppression des lignes, une seconde passe donne :

| Colonne | nombre de valeurs rares |
|-----:|:---|
|CODE_ETAPE| 2|
|LIBELLE_COURT_ETAPE| 1|
|LIBELLE_LONG_ETAPE| 1|

Une dernière passe confirme que la donnée est 5-anonymisée par cellule au sens où, pour chaque colonne, chaque valeur apparait au moins 5 fois.

Le nombre de lignes supprimées est de 795, partant de 213 289, il reste 212 494 lignes concernant 105 747 étudiant·e·s. La répartition des lignes supprimées par année n'est pas homogène, comme le montre le tableau `up13_perte.csv`.

| ANNEE | DONNEE_BRUTE | DONNEE_ANONYME | PERTE |
|-------:|-------------:|---------------:|-------:|
|  2006 |       20 040 |         19 995 |    45 |
|  2007 |       19 914 |         19 868 |    46 |
|  2008 |       19 897 |         19 856 |    41 |
|  2009 |       21 277 |         21 253 |    24 |
|  2010 |       21 022 |         20 972 |    50 |
|  2011 |       21 497 |         21 444 |    53 |
|  2012 |       22 355 |         22 292 |    63 |
|  2013 |       22 223 |         22 127 |    96 |
|  2014 |       22 423 |         22 274 |   149 |
|  2015 |       22 641 |         22 413 |   228 |

** Suite du texte d'accompagnement

Toutes les données suivantes sont produites en partant du tableau obtenu après le toilettage précédent.

#### Projection et k-anonymisation

Quatre jeux de données sont produits avec une même méthode d'anonymisation par suppression des lignes trop singulières. On sélectionne un certain nombre de colonnes du tableau et on supprime les lignes qui ne sont pas répétées au moins 5 fois.  C'est un compromis entre la possibilité de croiser des données et l'exhaustivité. En effet, plus il y a de colonnes plus il faut supprimer de lignes car les lignes sont de plus en plus spécifiques.

Un tout premier jeu de données `up13_anonyme.csv` fait le choix de conserver toutes les colonnes sauf l'identifiant de l'individu. On perd ainsi un maximum de lignes au moment de la 5-anonymisation : 129 742 lignes doivent être supprimées (soit 61% de la donnée initiale).

Pour les trois autres jeux de données on a choisi de ne pas aller au delà de 5% de pertes dans les lignes du tableau (en partant de la donnée avant toilettage initial donc en comptant les 795 lignes déjà perdues). Pour cela, on a choisi une ou deux colonnes particulières et on a étendu ce nombre de colonnes, en choisissant systématiquement la colonne suivante comme occasionnant le moins de nouvelles pertes.

Le tableau `up13_etapes.csv` concerne les étapes de diplôme, il contient les colonnes
"CODE_ETAPE", "LIBELLE_COURT_ETAPE", "LIBELLE_LONG_ETAPE", "NIVEAU_APRES_BAC", "LIBELLE_COURT_COMPOSANTE", "LIB_DIPLOME", "LIBELLE_DISCIPLINE_DIPLOME", "CODE_SISE_DIPLOME", "NIVEAU_DANS_LE_DIPLOME" et son anonymisation occasionne une perte supplémentaire de seulement 130 lignes.

Le tableau `up13_Academie.csv` concerne l'Académie du Bac et il contient les colonnes "LIBELLE_ACADEMIE_BAC", "NIVEAU_APRES_BAC", "NIVEAU_DANS_LE_DIPLOME", "CONTINENT", "LIBELLE_REGIME", "LIB_DIPLOME", "LIBELLE_COURT_COMPOSANTE" et son anoymisation implique la perte supplémentaire de 6 737 (soit une perte totale de 7532 lignes c'est à dire 3,5% de la donnée initiale).

Le tableau `up13_Bac.csv` concerne le type de Bac et le niveau atteint après le Bac, il contient les colonnes "REGROUPEMENT_BAC", "NIVEAU_APRES_BAC",  "LIBELLE_REGIME", "CONTINENT",  "LIBELLE_COURT_COMPOSANTE", "LIB_DIPLOME", "NIVEAU_DANS_LE_DIPLOME" et son anonymisation occasionne la perte supplémentaire de 3 145 lignes, donc 3 940 au total soit moins de 2% de la donnée initiale.

D'autres tableaux extraits de la même donnée initiale et construits selon la même méthode d'anonymisation, peuvent être fourni sur demande (préciser les colonnes souhaitées).

** Fin du texte d'accompagnement
#### Calcul des traces
Une trace s'obtient en suivant le parcours d'un individu dans l'Université via ses inscriptions successives et en oubliant les annnées auxquelles ont eu lieu ces inscriptions et les autres données sur l'individu (à l'exception de son type de Bac).

Deux types de traces sont déduites de la donnée. Les traces débutants par le type de Bac, dans le fichier `up13_traces_bac.csv` et les traces débutant immédiatement par la première inscription à l'université, dans le fichier `up13_traces.csv`.

Les traces identiques sont regroupées et dénombrées. Leur nombre est indiqué en première colonne et la trace occupe ensuite autant de colonnes qu'il y a eu d'années d'inscription par ordre croissant des années d'inscription (sans tenir compte de l'année de départ, des interruptions éventuelles, ou de la réussite au diplôme).

Par exemple, on trouve parmi les traces avec Bac la ligne suivante :

| Nombre | Trace            |                  |                  |
|-------:|:-----------------|:-----------------|:-----------------|
|    460 | Bacs généraux ES | IUTSD.DUT.1.S1TC | IUTSD.DUT.2.S2TC |

Elle signifie que sur les 10 années de 2006-2007 à 2015-2016, il y a eu 460 bachelier·e·s ES qui ont été inscrit·e·s à l'université Paris 13 en première année du DUT "S2TC" de l'IUT de Saint-Denis, puis en seconde année du même DUT sans autre inscription à l'université avant ou après (on ne sait pas s'il y a eu interruption entre les deux années de DUT, s'il a volonté de poursuite des études en 2016-2017, qui a réussi sa deuxième année et qui a échoué, on peut juste inférer une certaine réussite en première année).

Les traces singulières, c'est à dire concernant moins de 10 individus, sont publiées mais en mettant à 1 le nombre de personnes concernées (le nombre réel est entre 1 et 9).

Par exemple, la ligne suivante nous informe que entre un·e étudiant·e et 9 étudiant·e·s se sont inscrit·e·s en master 1 d'informatique puis en master 2 recherche programmation et logiciel sûr et uniquement ces deux inscriptions entre 2006 et 2015, en ayant une équivalence du Bac en poche.


| Nombre | Trace            |                  |                  |
|-------:|:-----------------|:-----------------|:-----------------|
| 1      | Equivalences     | IG.Master.4.G4INF | IG.Master Rec.5.G5PLS |

La présence ou l'absence d'une ligne correspondante dans les autres tableaux peut révéler des informations supplémentaires. Par exemple, s'il y avait la même ligne avec 8 autres Bac dans ce fichier et une ligne équivalente avec un nombre à 1 (donc de moins de 9 individus) dans le fichier de traces sans les Bacs, on pourrait déduire qu'une seule personne correspond à ce parcours. On pourrait aussi découvrir que depuis quelques années ce master est *indiférencié* (recherche et pro), et donc réduire la période à laquelle ce parcours a eu lieu. Il est donc important de ne pas diminuer trop les seuils d'anomysation (k = 5 ou k = 10 selon les cas) et éviter de permettre trop de croisements de données.

En tenant compte du type de Bac, il a 25 725 traces différentes :
- 42 460 étudiant·e·s laissent des traces singulières et produisent 23
  849 traces différentes (par souci d'anonymat on comptabilise
  faussement une seule personne par trace de chaque sorte, il pourrait y en avoir jusqu'à 9)
- et surtout *63 28 étudiant·e·s laissent une trace parmi 1 876 traces
  différentes* et l'anonymat étant respecté, on les dénombre précisément.

En ne tenant pas compte du Bac, on obtient 16 077 traces différentes dont :
-  24 583 étudiant·e·s laissant une trace singulière parmi 14 493 traces différentes (on compte faussement une seule personne par trace)
- et surtout *81 164 personnes laissent une trace parmi 1 584 traces différentes*.

* GTD
** TODO Faire un .md puis un epub et un pdf du texte d'accompagnement
** TODO Documenter le code, publier sur github ou autre plus libre
** TODO Une cellule rare supprime tout un parcours d'un id, pas seulement la ligne
** TODO Les items de traces (Bac + bla bla) ne contiennent pas d'information rare
** TODO pourquoi n'y a t'il pas de double diplome double étape ici ?
** TODO fournir plus d'explications sur le code pour les adresses pour Traces 02
** TODO Produire un discours orienté vers le grand public éduqué sur le respect des données personnelles
** TODO Préparer "Gardons le contact !"
* Traces (00 OLD)

Les traces sont extraites de la table =RESULTAT_VET= d'Apogée, qui
contient les résultats des étudiants aux /étapes/ de diplômes. Une
étape correspond en général à une année d'inscription. Une étape est
représentée par un code alphanumérique à 4-6 caractères comme G5PRLS
ou G5PLS. Une table =ETAPE= décrit les étapes.

La requête est la suivante :
#+BEGIN_SRC sql
select '(' || COD_IND ||', "'|| COD_ETP ||'", ' || COD_VRS_VET || ', ' || COD_ANU || ', ' || COD_SES || '),' from resultat_vet where COD_ADM = 1;

…
(<id_etudiant>, "G5PRLS", 316, 2016, 1)
(<id_etudiant>, "G5PRLS", 316, 2016, 2)
…

710897 lignes selectionnees.
#+END_SRC

On a filtré pour ne retenir que des résultats d'admission (=code_ADM =
1=), autrement nous aurions aussi des résultats d'admissibilité.

La colonne =COD_VERS_VET= contient un numéro de version dans l'étape.
Elle n'est pas utilisée par la suite. La dernière colonne dit s'il
s'agit d'un résultat du premier semestre, du second semestre ou
d'aucun semestre en particulier (0).

** Simplification par niveau

Première simplification : on ne regarde par si le résultat est bon ou
pas, on se contente de noter qu'un individu a suivi une étape jusqu'à
une épreuve d'admission.

Ces lignes sont ensuite organisées par individu en séquences
temporelles selon l'ordre des années et des semestres.

** Simplification par oubli du passé

On ne retient que les individus dont les traces commencent à partir
de 2007.


** Simplification des étapes multiples dans une année

Vient une simplification drastique : pour chaque année, on ne retient
qu'un seul code d'étape représentatif (en prenant le dernier de la
liste dans l'année). Une trace est alors une séquence de codes étapes,
un par année d'inscription. On perd ainsi les traces de doubles
inscriptions. Mais il est possible que l'alternance des années le
fasse réapparaître de façon curieuse : prenons un étudiants qui suit
L1DATA L2DATA L3DATA et en parallèle L1PHILO L2PHILO L3PHILO, on
pourra ici produire une trace L1PHILO-L2DATA-L3PHILO.

** Regroupement par traces identiques et anoymisation
Enfin on regroupe les individus par traces identiques.

Le résultat ne respecte pas le k-anonymat, au sens où de nombreuses
traces concernent moins de 4 ou 5 individus. Ces traces sont d'autant
plus nombreuses que certaines étapes ont légèrement changé de nom dans
le temps (par exemple, G5PLS remplacé par G5PRLS).

#+BEGIN_SRC txt
G5PRLS; 2; M; Master2 Ind Programmation et Logiciels Surs; Master2Ind PLS
G5PLS; 2; M; Master2 Programmation et Logiciels surs; Master2 Prog Log Surs
G5EID; 2; M; Master2 INFO-EID; Master2 INFO-EID
G5EID3; 2; M; Master2 INFO-EID (FC); Master2 INFO-EID (FC)
G5EI; 2; M; DESS EXPLORATION INFORMATIQUE DES DONNEES; DESS EXPLORATION INF DON
G5EI2D; 2; M; Master2 Ind Exploration Informatique Donnees et Decisionnel; Master2Ind EI2D

#+END_SRC


#+BEGIN_SRC sh
> P0:apotraces$ grep G5PRLS output.txt
V1IN-V2IN-G3INF-G4INF-G5PRLS 1
A3CIW-G4INFO-G5PRLS 1
G1INF-G2INF-G3INF-G4INF-G5PRLS 1
V1IN-V2IN-G5PRLS 1
G3SPI-G4INFO-G5PRLS 1
G1TRC-G1INF-G2INF-G2INF-G3INF-G4INFO-G5PRLS 1
G1TRC-G2SPI-G2SPI-G1INF-G2INF-G3INF-G4INFO-G5PRLS 1
G1TRC-G1TRC-G1INF-G2INF-G3INF-G4INF-G5PRLS 1
G3INF-G4INF-G4INF-G5PRLS-G5PRLS 1
G2INF-G2INF-G3INF-G3INF-G4INF-G5PLS-G5PRLS 1
G1TRC-G1PC-G2INF-G3INF-G4INF-G5PRLS 1
G1TRC-G1INF-G2INF-G3INF-G4INF-G5PRLS 1
V1EI-V2EI-G2INF-G3INF-G4INF-G5PRLS 1
G3INF-G4INFO-G4INFO-G5PRLS 1
G1INF-G1INF-G1INF-G2INF-G3INF-G4INFO-G5PRLS 1
G4INF-G5PRLS-G8IN-G8IN 1
G4INF-G4INF-G5PLS-G5PRLS 1
G1INF-G2INF-G3INF-G3SI-G4INFO-G5PRLS 1
G3SI-G3SI-G4INFO-G5PRLS 1
V1IDA-V2IDA-V2IDB-G3INF-G4INF-G5PRLS 1
G3INF-G4INF-G4INF-G5PLS-G5PRLS 1
G1SPI-G2SPI-G3ST-G4ST-G5ST-G5PRLS 1
G1TRC-G1TRC-G2INF-G2INF-G2INF-G3INF-G3INF-G4INFO-G4INFO-G5PRLS 1
G4INFO-G4INFO-G5PRLS 1
G3INF-G4INF-G4INFO-G5PRLS 1
G3INF-G3INF-G4INF-G4INF-G5PRLS-G5PRLS 1
G4IR-G5PRLS 1
G3INF-G3INF-G4INF-G5PLS-G5PRLS 1
G4INF-G5PRLS 1
G4INF-G4INF-G5ITC-G5PLS-G5PLS-G5PRLS 1
G2INF-G2INF-G3INF-G4INF-G4INF-G5PRLS 1
S1IM-S2IM-G3SPI-G4IR-G5PRLS 1
G1INF-G2INF-G1INF-G2INF-G3INF-G4INFO-G5PRLS 1
V1RT-V1RT-V2RT-G2INF-G3INF-G4INFO-G5PRLS 1
G4INF-G4INF-G4INF-G5PRLS 1
G1INF-G2INF-G3INF-G4INF-G4INFO-G5PRLS 1
V1IN-V1IN-V2IN-G3INF-G4INFO-G5PRLS 1
G4INF-G4INF-G5PRLS-G5PRLS 1
V1IN-V1IDB-V2IDB-G3INF-G4INFO-G5PRLS 1
G1TRC-G2INF-G2INF-G3INF-G3INF-G4INFO-G5PRLS 1
G3INF-G4INF-G4INF-G5PRLS 1
G3INF-G5PRLS 1
G1MAT-G2INF-G3INF-G4INFO-G5PRLS 1
G1INF-G2INF-G3INF-G4INFO-G4INFO-G5PRLS 1
G4INF-G4INF-G5PRLS 1
G1INF-G2INF-G3INF-G3INF-G4INFO-G5PRLS 1
G1INF-G2INF-G2INF-G3INF-G4INFO-G5PRLS 1
G1PI-G2PI-G2INF-G2INF-G3INF-G4INF-G5PRLS 1
G1TRC-G1TRC-G2INF-G2INF-G3INF-G4INF-G5PRLS 2
V1IN-V2IN-G3INF-G4INFO-G5PRLS 2
G3INF-G4INF-G5PRLS 2
G2INF-G3INF-G4INFO-G5PRLS 2
V1IN-V2IN-V2IDB-G3INF-G4INFO-G5PRLS 2
G3INF-G4INF-G5PLS-G5PRLS 2
G3INF-G3INF-G4INFO-G5PRLS 2
G4INF-G4INFO-G5PRLS 3
G3INF-G4INFO-G5PRLS 3
G1INF-G2INF-G3INF-G4INFO-G5PRLS 5
G1INF-G1INF-G2INF-G3INF-G4INFO-G5PRLS 8
G4INFO-G5PRLS 12
G5PRLS 15

P0:apotraces$ grep G5PLS output.txt
B1SVI8-B1SVI8-G1TRC-G2INF-G3INF-G4INF-G5PLS 1
G4INF-G4INF-G5PLS-G5PLS 1
G4INF-G4INF-G4INF-G5PLS 1
G5SIM-G5PLS-G8SEI-G8SEI-G8SEI-G8SEI 1
A3AG-G4INF-G5PLS 1
G4IR-G5RIM-G5PLS 1
G1TRC-G2INF-G2INF-G3INF-G4INF-G5PLS 1
G2INF-G2INF-G3INF-G3INF-G4INF-G5PLS-G5PRLS 1
G1TRC-G2MAT-G3MAT-G3MAT-G4INF-G5PLS 1
V1IN-V2IN-V3SI-G4INF-G5PLS 1
G3INF-G3INF-G4INF-G5PLS-G5PLS 1
G4INF-G4INF-G5PLS-G5PRLS 1
G3INA-G4INF-G5PLS-G5PLS 1
G3INF-G4INF-G4INF-G5PLS-G5PRLS 1
LUFE-G4INF-G5PLS 1
G3INF-G3INF-G4INF-G5PLS-G5PRLS 1
G3INA-G4INF-G5PLS 1
G4INF-G4INF-G5ITC-G5PLS-G5PLS-G5PRLS 1
V3SI-G4INF-G4INF-G5PLS 1
G3INF-G4IR-G5PLS 1
V3SI-G4INF-G5PLS 1
G1TRC-G5PLS 1
V1IN-V2IN-G3INF-G4INF-G5PLS 1
A3CIW-G4INF-G5PLS 1
G4IR-G5PLS 1
G1CP-G2INF-G3SI-G4SI-G5SI-G5PLS-G8IN-G8IN-G8IN 1
G2INF-G3INF-G4INF-G5PLS 2
G3INF-G4INF-G5PLS 2
G5PLS-G5PLS 2
G3INF-G4INF-G5PLS-G5PRLS 2
G5PLS-G8IN-G8IN-G8IN-G8IN 2
G1TRC-G1TRC-G2INF-G3INF-G4INF-G5PLS 3
G4INF-G5PLS-G5PLS 3
G3INF-G3INF-G4INF-G5PLS 4
G4INF-G4INF-G5PLS 5
G1TRC-G2INF-G3INF-G4INF-G5PLS 9
G4INF-G5PLS 13
G5PLS 23
#+END_SRC

Pour achever l'anonymisation,
